### ISSUE TITLE
No such classes in the latest netty.jar now

### ISSUE THREAD

**Issue by caidollar** [zhoumengkang/netty-restful-server#3]
I used the jar file netty-all-4.1.0.CR7.
And foud that there're no following classes now:
1. io.netty.handler.codec.AsciiString;
2. io.netty.handler.codec.http.HttpHeaderUtil

**Comment by zhoumengkang** [comment]
Netty version is 5.0.0.Alpha2 int this project. You can get the version by searching `netty.version` in pm.xml.
