### ISSUE TITLE
Could you please clarify license of your code

### ISSUE THREAD

**Issue by maxott** [zhoumengkang/netty-restful-server#4]
Thanks for providing this project. Could you please add a license declaration to your code. Would help me with the "suits" :)

**Comment by zhoumengkang** [comment]
I am very happy to share this project for everyone, but I don't know what license should be added. If you want, pick it and use it anywhere you want.
By the way, can you give me some advice for the license declaration.

**Comment by maxott** [comment]
Sorry for not responding earlier. I fully understand your intent, it's just to keep the lawyers happy for those of us having to worry about them :) The simplest and most widely used license in this context would be the MIT one - https://opensource.org/licenses/MIT. There are a couple of others - potentially more humorous, such as the [WTFPL](https://en.wikipedia.org/wiki/WTFPL), but they often come with legal uncertainties :) In short, MIT is my usual choice of license if I want to make it as easy as possible for others to use it.

**Comment by zhoumengkang** [comment]
https://github.com/zhoumengkang/netty-restful-server/blob/master/license.txt
